### ISSUE TITLE
replay mod crash

### ISSUE THREAD

**Issue by makerio90** [rebane2001/livemessage#3]
it crashes when using the replay mod

**Comment by rebane2001** [comment]
Could you provide the crash logs? If the logs don't appear for you, choose "Open output log when Minecraft: Java Edition starts" from your Minecraft Launcher settings.

**Comment by mr-nv** [comment]
newer versions of replay mod are known to be incompatible with quite a lot of popular mods [(read this)](https://github.com/ReplayMod/ReplayMod/blob/develop/docs/content.md#unsupported-launchers-launchers)
try using the 2.2.0-b7 version of replay mod

**Comment by makerio90** [comment]
> Could you provide the crash logs? If the logs don't appear for you, choose "Open output log when Minecraft: Java Edition starts" from your Minecraft Launcher settings.

```
[16:10:21] [main/INFO] [LaunchWrapper]: Calling tweak class com.replaymod.core.tweaker.ReplayModTweaker
16:10:21.408
```

```
[java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.launch.platform.MainAttributes from class org.spongepowered.asm.launch.platform.container.ContainerHandleURI
16:10:21.409

```
```
[java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.container.ContainerHandleURI.<init>(ContainerHandleURI.java:58)
16:10:21.410
```

```
[java.lang.ThreadGroup:uncaughtException:1052]: 	at com.replaymod.core.tweaker.ReplayModTweaker.injectIntoClassLoader(ReplayModTweaker.java:78)
16:10:21.410

```
```
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
16:10:21.410
```

```
[java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
16:10:21.539
```

```
monitor
Process Monitor
Process crashed with exit code 1
```

**Comment by rebane2001** [comment]
Added information in the FAQ about how to get Replay Mod to work 🎉

**Comment by Johni0702** [comment]
Why not just update Mixin to 0.8? This issue isn't specific to ReplayMod, it'll happen with any mod which depends on Mixin 0.8 because you're still bundling 0.7.x.

> try using the 2.2.0-b7 version of replay mod

Great way to enjoy the dozens of bugs (including replay corrupting ones) which have been fixed since.

> newer versions of replay mod are known to be incompatible with quite a lot of popular mods [(read this)](https://github.com/ReplayMod/ReplayMod/blob/develop/docs/content.md#unsupported-launchers-launchers)

FTR, all of those are issues (sometimes even deliberate) in the third-party mod/client. None of them can be fixed by the ReplayMod itself, hence why listing them in the FAQ is the most we can do.

**Comment by rebane2001** [comment]
> This issue isn't specific to ReplayMod

Anecdotically it is, I've never seen this much incompatibility with any other 1.12.2 mod I've used, I had no idea it was caused *only* by the Mixin version. I think this fact should be made more clear in the Replay Mod documentation so mod authors know what's causing it, the current wording of "is not compatible with the Mixin" makes it sound like the mixins themselves are conflicting, not the Mixin version (@Johni0702).

Anyways, I've made a [new release](https://github.com/rebane2001/livemessage/releases/tag/v1.0.2) that uses a later Mixin to solve this issue properly.

**Comment by Johni0702** [comment]
> Anecdotically it is, I've never seen this much incompatibility with any other 1.12.2 mod I've used, I had no idea it was caused only by the Mixin version.

https://github.com/Johni0702/BetterPortals/issues?q=is%3Aissue+mixin+is%3Aclosed
BP is a mod I'm no longer updating which still ships Mixin 0.7 and it's been causing tons of issues (doesn't help that its name starts with B so its mixin usually gets priority over other ones).

> I think this fact should be made more clear in the Replay Mod documentation so mod authors know what's causing it, the current wording of "is not compatible with the Mixin" makes it sound like the mixins themselves are conflicting, not the Mixin version (@Johni0702).

That wording was specific to Future Client, in which case I believe it is actually both. For LiteLoader where it's really just the version it bundles, the FAQ says "LiteLoader is known to cause issues due to the mixin version it contains".
Anyhow, there's indeed no section about Mixin 0.7 compatibility in general, I suppose one could be added.

> Anyways, I've made a new release that uses a later Mixin to solve this issue properly.

:partying_face:

**Comment by makerio90** [comment]
i don't understand. what do i have to upgrade/downgrade?

**Comment by rebane2001** [comment]
@makerio90 Upgrade to the latest release of Livemessage. If you're still having problems, let me know (but make sure the problem is caused by only Livemessage/ReplayMod and not any other mods).
